### ISSUE TITLE
Error,Cannot make fucntion

### ISSUE THREAD

**Issue by samp-pinch** [BoxOfDevs/Functions#8]
I cannot create function. Read copy .log fir details.

# Logs/Errors

> function c Hub

Warning: file_put_contents(/storage/emulated/0/PocketMine/plugins/Functions/config.yml): failed to open stream: No such file or directory in /storage/emulated/0/PocketMine/src/pocketmine/utils/Config.php on line 207

Warning: file_put_contents(/storage/emulated/0/PocketMine/plugins/Functions/config.yml): failed to open stream: No such file or directory in /storage/emulated/0/PocketMine/src/pocketmine/utils/Config.php on line 207

Warning: file_put_contents(/storage/emulated/0/PocketMine/plugins/Functions/config.yml): failed to open stream: No such file or directory in /storage/emulated/0/PocketMine/src/pocketmine/utils/Config.php on line 207

Notice: Undefined variable: name in /storage/emulated/0/PocketMine/plugins/Functions-master/src/Ad5001/Functions/Main.php on line 47

Notice: Undefined variable: cmd in /storage/emulated/0/PocketMine/plugins/Functions-master/src/Ad5001/Functions/Main.php on line 48
[Tesseract] [20:56:12] INFO> [Functions] Function Hub has been created! You can edit it on the config or by doing /function ac <function> <command number> <command...>.
> function ac Hub 1 kill

Warning: file_put_contents(/storage/emulated/0/PocketMine/plugins/Functions/config.yml): failed to open stream: No such file or directory in /storage/emulated/0/PocketMine/src/pocketmine/utils/Config.php on line 207
[Tesseract] [20:56:21] INFO> [Functions] Function Hub not found. Create it with /function c Hub

But I alredy do /function create Hub and again this last msg

**Comment by HimbeersaftLP** [comment]
Looks like a permission problem, try (on Linux console, go in the folder with your functioms config first) "chown username config.yml" (replace username with the user you are running the server with)

**Comment by Ad5001** [comment]
Is the data folder created? Did you delete the config.yml?

**Comment by samp-pinch** [comment]
I'll try :D

**Comment by samp-pinch** [comment]
Man there is no Functions folder

Its not created

**Comment by samp-pinch** [comment]
Hmm man,I probably know how to fix,can u give me some rank to can contribute??

**Comment by samp-pinch** [comment]
Fixed it local

**Comment by kabluinc** [comment]
Please can you give me updated version or fix it. I'm getting these errors

Notice: Undefined variable: name in C:\Desktop\New folder (10)\plugins\Functions-master\src\Ad5001\Functions\Main.php on line 47

Notice: Undefined variable: cmd in C:\Desktop\New folder (10)\plugins\Functions-master\src\Ad5001\Functions\Main.php on line 48

**Comment by kabluinc** [comment]
and some more errors

Notice: Undefined offset: 1 in C:\Desktop\New folder (10)\plugins\Functions-master\src\Ad5001\Functions\Main.php on line 162

Notice: Undefined offset: 2 in C:\Desktop\New folder (10)\plugins\Functions-master\src\Ad5001\Functions\Main.php on line 166

Notice: Array to string conversion in C:\Desktop\New folder (10)\plugins\Functions-master\src\Ad5001\Functions\Main.php on line 167

Notice: Undefined offset: 3 in C:\Desktop\New folder (10)\plugins\Functions-master\src\Ad5001\Functions\Main.php on line 171

Notice: Undefined offset: 4 in C:\Desktop\New folder (10)\plugins\Functions-master\src\Ad5001\Functions\Main.php on line 173

**Comment by Ad5001** [comment]
Will see about this...

**Comment by Ad5001** [comment]
Ok look at the new commit, should be fixed.

**Comment by kabluinc** [comment]
Still shows this when starting.
`Warning: file_put_contents(C:\Desktop\New folder (10)\plugins\Functions/config.yml): failed to open stream: No such file or directory in C:\Users\Gamer27832 server\Desktop\New folder (10)\src\pocketmine\utils\Config.php on line 208
`

Then this after I manually copy the folder

`Notice: Undefined variable: name in C:\Desktop\New folder (10)\plugins\Functions-master\src\Ad5001\Functions\Main.php on line 24

Notice: Undefined variable: name in C:\Desktop\New folder (10)\plugins\Functions-master\src\Ad5001\Functions\Main.php on line 24

Notice: Undefined variable: name in C:\Desktop\New folder (10)\plugins\Functions-master\src\Ad5001\Functions\Main.php on line 24

Notice: Undefined variable: name in C:\Desktop\New folder (10)\plugins\Functions-master\src\Ad5001\Functions\Main.php on line 24

Notice: Undefined variable: name in C:\Desktop\New folder (10)\plugins\Functions-master\src\Ad5001\Functions\Main.php on line 24

Notice: Undefined variable: name in C:\New folder (10)\plugins\Functions-master\src\Ad5001\Functions\Main.php on line 24

Notice: Undefined variable: name in C:\Desktop\New folder (10)\plugins\Functions-master\src\Ad5001\Functions\Main.php on line 24

Notice: Undefined variable: name in C:\Desktop\New folder (10)\plugins\Functions-master\src\Ad5001\Functions\Main.php on line 24`

when running the function I created it says unknown command

**Comment by samp-pinch** [comment]
I alrefy try,that bro local,and not work

**Comment by samp-pinch** [comment]
Alredy

**Comment by Ad5001** [comment]
Should be fixed now.

**Comment by kabluinc** [comment]
Sorry for troubling you however when I start server, it shows this on plugin load "Notice: Undefined variable: name in C:\Desktop\New folder (10)\plugins\Functions-master\src\Ad5001\Functions\Main.php on line 24
"

In-game the command doesn't work and only works with "./". No errors in console

**Comment by kabluinc** [comment]
btw. A new config is not created because the config u put in "resources" folder is a .properties file. It should be .YML

**Comment by Ad5001** [comment]
With the new commit, it should be fixed

**Comment by samp-pinch** [comment]
Ad5001 bro trust me,u cannot do it...its impssible from 0.17+ (I meant where when u type / its show list)

**Comment by Ad5001** [comment]
It should show.

**Comment by kabluinc** [comment]
Still the commands made using functions dont show up or work. Just says unknown command. Forexample /hub doesnt work but ./hub does

**Comment by HimbeersaftLP** [comment]
That's a bug in the Server Software (which will be fixed soon I hope).

They don't show up because they aren't registered as commands.

**Comment by Ad5001** [comment]
MCPE is not registering after joined commands. Try rejoning / retstart your server.

**Comment by HimbeersaftLP** [comment]
> They don't show up because they aren't registered as commands.

...in MCPE, forgot to say that xD

**Comment by kabluinc** [comment]
Even after rejoining and restarting server, the commands are not registered. Still show unknown command

**Comment by Ad5001** [comment]
So that's a MCPE bug we cannot do anything about it (the command with a dot before is the same code as the normal ones) Do it with a dot. We cannot do anything about it.

**Comment by kabluinc** [comment]
Thanks for trying

**Comment by HimbeersaftLP** [comment]
> So that's a MCPE bug we cannot do anything about it (the command with a dot before is the same code as the normal ones) Do it with a dot. We cannot do anything about it.

Isn't it a server issue because of the way commands are handled im 1.0 zhe devs had to add a hack for the commands, so it's basically a server software issue, but it's Mojangs fault xD

**Comment by remotevase** [comment]
I tried using Tesseract and the regular / commands work fine

**Comment by HimbeersaftLP** [comment]
Here we go lol
